let webpack = require('webpack');
let path = require('path');

module.exports = {

    // debugging easier , which files has error
    devtool:'inline-source-map', // eval-source-map

    entry: {
        'index': './src/index.js'
    },

    output: {
        path: path.resolve(__dirname, 'dist'),
        filename: 'main.js'
    },

    //where to use the loader
    module: {
        rules: [ //multiple rules // inside reate diffrent 
            { //babel use garera es6 .7 es5 broser garna sagelo hunxa 
                //use babel on which files
                test: /\.js$/, //regex start with// end-> $
                exclude: "/node_modules/",
                use: 'babel-loader'
            },
            //for css files
            {
                test:/\.css$/,
                exclude:/node_modules/,
                use:['style-loader','css-loader'] // to convert css to js
            // from right first css loader second style loader
            }
        ]
    },
    devServer: {
        // those content that are not generated by webpack
        contentBase: path.join(__dirname, "public/"),
        port: 3000,
        // to serve webpack files 
        // HMR reloading 
        hot:true,
        publicPath: "http://localhost:3000/dist/"
    }

}